
name: containerd

on:
  push:
    branches:
      - main

jobs:
  containerd:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up containerd
        uses: crazy-max/ghaction-setup-containerd@v3
        with:
          config-inline: |
                version = 2

                # - Set default runtime handler to v2, which has a per-pod shim
                # - Enable to use stargz snapshotter
                [plugins."io.containerd.grpc.v1.cri".containerd]
                  default_runtime_name = "runc"
                  snapshotter = "stargz"
                  disable_snapshot_annotations = false
                [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                  runtime_type = "io.containerd.runc.v2"

                # Setup a runtime with the magic name ("test-handler") used for Kubernetes
                # runtime class tests ...
                [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.test-handler]
                  runtime_type = "io.containerd.runc.v2"

                # Use stargz snapshotter
                [proxy_plugins]
                  [proxy_plugins.stargz]
                    type = "snapshot"
                    address = "/run/containerd-stargz-grpc/containerd-stargz-grpc.sock"

      -
        name: See config
        run: |
          containerd config default > /tmp/containerd-config.toml
          cat /tmp/containerd-config.toml



