
name: containerd

on:
  push:
    branches:
      - main

jobs:
  containerd:
    runs-on: ubuntu-latest
    steps:
      -
        name: ctr-remote pull openpilot
        run: |
          ctr-remote image pull ghcr.io/commaai/openpilot/openpilot-base:latest
