name: containerd

on:
  push:
    branches:
      - main

jobs:
  containerd:
    runs-on: ubuntu-latest
    steps:
      -
        name: update containerd config file
        run: |

          containerd --version
          docker --version
          docker buildx version
          sudo systemctl status containerd
          sudo systemctl status docker

          sudo cat /etc/containerd/config.toml
          sudo bash -c 'cat << EOF >> /etc/containerd/config.toml
          version = 2

          [proxy_plugins]
            [proxy_plugins.stargz]
              type = "snapshot"
              address = "/run/containerd-stargz-grpc/containerd-stargz-grpc.sock"
          EOF'
          sudo cat /etc/containerd/config.toml

          sudo cat /etc/docker/daemon.json
          sudo bash -c 'cat << EOF >> /etc/docker/daemon.json
          {
            "features": {
              "containerd-snapshotter": true
            },
            "storage-driver": "stargz"
          }
          EOF'

          sudo cat /etc/docker/daemon.json

      -
        name: install + restart services
        run: |
          sudo apt-get install fuse
          sudo modprobe fuse
          sudo wget https://github.com/containerd/stargz-snapshotter/releases/download/v0.15.1/stargz-snapshotter-v0.15.1-linux-amd64.tar.gz
          sudo tar -C /usr/local/bin -xvf stargz-snapshotter-v0.15.1-linux-amd64.tar.gz containerd-stargz-grpc ctr-remote
          sudo wget -O /etc/systemd/system/stargz-snapshotter.service https://raw.githubusercontent.com/containerd/stargz-snapshotter/v0.15.1/script/config/etc/systemd/system/stargz-snapshotter.service
          sudo systemctl enable --now stargz-snapshotter
          sudo systemctl restart containerd
          sudo systemctl restart docker

          sudo systemctl status stargz-snapshotter
          sudo systemctl status containerd
          sudo systemctl status docker

      -
        name: docker images
        run: |

          docker buildx create --use --name lazy-builder --buildkitd-flags '--oci-worker-snapshotter=stargz'
          docker buildx inspect --bootstrap lazy-builder

          docker buildx build --load -t hello-org -f Dockerfile.stargz-org .
          docker run --rm hello-org

          docker buildx build --load -t hello-esgz f Dockerfile.stargz-esgz .
          docker run --rm hello-esgz
