
name: containerd

on:
  push:
    branches:
      - main

jobs:
  containerd:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up containerd
        uses: crazy-max/ghaction-setup-containerd@v3
      -
        name: See config
        run: |

          sudo cat /etc/containerd/config.toml

          sudo echo '# Enable stargz snapshotter for CRI
                [plugins."io.containerd.grpc.v1.cri".containerd]
                  snapshotter = "stargz"
                  disable_snapshot_annotations = false

                # Plug stargz snapshotter into containerd
                [proxy_plugins]
                  [proxy_plugins.stargz]
                    type = "snapshot"
                    address = "/run/containerd-stargz-grpc/containerd-stargz-grpc.sock"' >> /etc/containerd/config.toml

          sudo cat /etc/containerd/config.toml


