
name: containerd

on:
  push:
    branches:
      - main

jobs:
  containerd:
    runs-on: ubuntu-latest
    steps:
      -
        name: check if containerd is isntalled
        run: |
          containerd --version
          ctr --version
          sudo cat /etc/containerd/config.toml
