name: stargz-test

on:
  push:
    branches:
      - main

jobs:
  containerd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Do I need this? https://github.com/containerd/stargz-snapshotter/blob/main/docs/INSTALL.md
      # -
      #   name: update containerd config file
      #   run: |

      #     containerd --version
      #     docker --version
      #     docker buildx version

      #     sudo systemctl status containerd
      #     sudo systemctl status docker

      #     sudo cat /etc/containerd/config.toml
      #     sudo bash -c 'cat << EOF >> /etc/containerd/config.toml
      #     version = 2

      #     [proxy_plugins]
      #       [proxy_plugins.stargz]
      #         type = "snapshot"
      #         address = "/run/containerd-stargz-grpc/containerd-stargz-grpc.sock"
      #     EOF'
      #     sudo cat /etc/containerd/config.toml

      #     sudo cat /etc/docker/daemon.json
      #     sudo bash -c 'cat << EOF >> /etc/docker/daemon.json
      #     {
      #       "features": {
      #         "containerd-snapshotter": true
      #       },
      #       "storage-driver": "stargz"
      #     }
      #     EOF'

      #     sudo cat /etc/docker/daemon.json

      # -
      #   name: install + restart services
      #   run: |
      #     sudo apt-get install fuse
      #     sudo modprobe fuse
      #     sudo wget https://github.com/containerd/stargz-snapshotter/releases/download/v0.15.1/stargz-snapshotter-v0.15.1-linux-amd64.tar.gz
      #     sudo tar -C /usr/local/bin -xvf stargz-snapshotter-v0.15.1-linux-amd64.tar.gz containerd-stargz-grpc ctr-remote
      #     sudo wget -O /etc/systemd/system/stargz-snapshotter.service https://raw.githubusercontent.com/containerd/stargz-snapshotter/v0.15.1/script/config/etc/systemd/system/stargz-snapshotter.service
      #     sudo systemctl enable --now stargz-snapshotter
      #     sudo systemctl restart containerd || true
      #     sudo systemctl status containerd.service
      #     sudo journalctl -xeu containerd.service
      #     sudo systemctl restart docker

      #     sudo systemctl status stargz-snapshotter
      #     sudo systemctl status containerd
      #     sudo systemctl status docker
      #     exit 1
      -
        name: env info
        run: |
          containerd --version
          docker --version
          docker buildx version
      -
        name: build/pull normal image
        run: |
          docker buildx build --pull -t hello-org -f Dockerfile.stargz_org .
          docker run hello-org -d

      -
        name: build/pull stargz image
        run: |
          docker buildx create --use --name lazy-builder --buildkitd-flags '--oci-worker-snapshotter=stargz'
          docker buildx inspect --bootstrap lazy-builder
          docker buildx build --pull -t hello-esgz -f Dockerfile.stargz_esgz .
          docker run hello-esgz -d


